[build]
  command = "npm run build"
  functions = "lambda-functions"
  publish = "build"

# [[redirects]]
#   from = "/login"
#   to = "https://todo-app-lp.netlify.app"
#   status = 200
#   force = true
#   headers = {X-From = "Netlify"}

# [[redirects]]
#   from = "/logout"
#   to = "https://todo-app-lp.netlify.app"
#   status = 200
#   force = true
#   headers = {X-From = "Netlify"}

# [[redirects]]
#   from = "/register"
#   to = "https://todo-app-lp.netlify.app"
#   status = 200
#   force = true
#   headers = {X-From = "Netlify"}

# [[redirects]]
#   from = "/todo"
#   to = "https://todo-app-lp.netlify.app"
#   status = 200
#   force = true
#   headers = {X-From = "Netlify"}
