[build]
  command = "npm run build"
  functions = "lambda-functions"
  publish = "build"

[[redirects]]
  from = "/.netlify/functions/server/login"
  to = "https://todo-app-lp.netlify.app/.netlify/functions/server/login"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/.netlify/functions/server/logout"
  to = "https://todo-app-lp.netlify.app/.netlify/functions/server/logout"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/.netlify/functions/server/register"
  to = "https://todo-app-lp.netlify.app/.netlify/functions/server/register"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/.netlify/functions/server/todo"
  to = "https://todo-app-lp.netlify.app/.netlify/functions/server/todo"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
